info:
  contact: {}
  description: This is a sample server.
  title: Swagger Example API
paths:
  /api/hello:
    get:
      description: Hello example
      produces:
      - text/plain
      responses:
        "200":
          description: hello
          schema:
            type: string
      summary: Hello
swagger: "2.0"
